### PR TITLE
Fix issue #36

### PR DESCRIPTION
**Pull request by mkoertgen**

### CODE REVIEW

**Comment by mkoertgen** [comment]
Made the PR a wip. It fixes the NRE but now we have empty coverage files with OpenCover...

**Comment by mkoertgen** [comment]
Ok, noticed a change in behaviour. Up to now i used

```bash
coveralls.net.exe --opencover *.Coverage.xml
```
The code seems to expect specifying the search pattern now , i.e.  

```bash
coveralls.net.exe --opencover -f *.Coverage.xml
```

However, using the `f`-switch results in an `InvalidOperationException` because the `f`-switch has been registered twice as a command line option (`full-sources`).

**Comment by mkoertgen** [comment]
Renamed the short option to `t`.

Workaround for the command line is to specify the current directory as `input file`, i.e.

```bash
coveralls.net.exe --opencover . -t *.Coverage.xml
```

**Comment by mkoertgen** [comment]
Ok, i changed the a bit so the CLI behavior matches that of the previous version 1.3.4.

I renamed the short-option for `full-sources` to `s` so we don't have any breaking changes.

**Comment by jdeering** [comment]
A lot of the changes in this pull request are not necessary and have no bearing on fixing the issue. A lot of it looks like IDE-automated stuff and/or from a clean-up tool. I hate to be nitpicky, but some of the variable naming decisions made (capitalization, readonly vs. not, etc.) are subjective and I do not want those types of changes implemented without reason or discussion. Please revert some of the "clean-up" type things and have only the changes needed to remedy the issue and associated tests included.

Thank you for contributing. I'm always excited to have help maintaining this project.

**Comment by mkoertgen** [comment]
No offense, i followed the pathfinder's rules and wanted to cleanup some things along the way. I noticed the repo could use some cleanup, e.g. some dependencies are not maintained any longer (CommandLine). I agree that this should probably go into a separate issue.

Anyway, i reverted the cleanup stuff and squashed the commits. Please review and have an updated package pushed out to NuGet

**Comment by jdeering** [comment]
@mkoertgen Thanks for the help on this. 

If you have the time to run a cleanup branch, feel free. I just prefer to have changes segregated into branches in fairly tight units. It makes it easier to do these reviews as well as run down any issues that pop up from a set of changes.

**Pull request merged**
