### PR TITLE
Added .NET Core support & updated dependencies

### PR DESCRIPTION
**Pull request by luvies**
I've added a second solution that contains all of the .NET Core projects, and have updated the projects in order to get it working with the new target. Unfortunately, a number of the dependencies were out of date (and it meant that they didn't have .NET Standard support), so I've had to bring them up to the latest versions so both projects work nicely together (and actually build). It also meant that I had to updated the target .NET Framework version to 4.6.2, however this shouldn't change much.

All tests pass on both targets. The `dotnet` command can be used to build and test both versions now, but Visual Studio also still works. Note, I had to delete the `bin` and `obj` directories for each project to allow it to build for the new .NET Framework target.

I also set up the .NET Core version of the `coveralls.net` project to output in a dotnet-tool compatible format, so people using .NET Core can install the project using the `DotNetCliToolReference` tag in their `csproj`. Once they do, they can use `dotnet coveralls` to execute the app as normal. I have also provided the necessary config items to allow global tool support, meaning that once .NET Core 2.1 is out, you can just bump the version and it will support it.

### CODE REVIEW

**Comment by luvies** [comment]
I can merge the solutions together if it is needed, but I think the AppVeyor config will need altering for the .NET Core support.

Edit: I haven't adjusted the main project version, so the file produced when calling `dotnet pack` on the main project has the version `1.0.0`. I can alter the version to match current if needed.

**Comment by luvies** [comment]
I've merged the project files together to make them easier to manage. I've also added .NET Core 2.1 support, so global tool support should now work. All tests pass on my end, however AppVeyor still needs to be updated with the .NET Core 2.1 SDKs (should happen within a week of this comment), and the `appveyor.yml` file needs updating to work with the different SDK setup (since it nows uses the `dotnet` command to build and test).

**Comment by luvies** [comment]
This would also close #28

**Comment by fuzzzerd** [comment]
This looks like it would make adding coverall support to .NET Core projects a lot easier; is there any hope this will eventually be merged?

**Comment by luvies** [comment]
Not sure, there hasn't been any action on this repo in a while, so I'm not sure how much support it is still getting. I don't know if it's because the check fails that they simply haven't done anything with this (which would be really annoying, since all they need to do is at least mention that), however I know the tests pass (I did it on my machine when making this, for both .NET Framework and .NET Core), so it's purely a case of adjusting the appveyor config (since this isn't my repo, I'm not confident that I'll be able to edit it to how they'd want it, but if they just mentioned it, I can makes changes, but I also don't use appveyor, so I don't know the config from the top of my head and would need to research a little first).

**Comment by jasondeering** [comment]
I am still maintaining this as I'm able with what little free time I have. I'll pull this down locally and see if I can spot the issue. If it's just AppVeyor being annoying or not supporting something, then I can work everything locally and get a new version published.

**Comment by devlead** [comment]
@jasondeering issue is likely that `image: Visual Studio 2017` needs to be added to [appveyor.yml](https://github.com/coveralls-net/coveralls.net/blob/68bb92d9954e93608636fb5251a2fd9a13ba0677/appveyor.yml#L2).

**Comment by devlead** [comment]
@luvies you should be able to add this in the PR and se if it builds.

**Comment by devlead** [comment]
@luvies Sent a PR so it compiles luvies/coveralls.net#1, feel free to steal that to this pr or just merge I think I target same branch as this PR ;)

**Comment by luvies** [comment]
Thank you @devlead for the quick fix, it would have taken me some time to properly work that out & I wouldn't have been able to test it without setting up the CI myself

**Comment by devlead** [comment]
@luvies no worries, hope to use the tool soon 😉

**Comment by jdeering** [comment]
@luvies @devlead 
Thanks for your work on this, guys!

**Pull request merged**
